# Generated by Django 4.2.1 on 2023-08-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_studentdata_id_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_marks',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='first_app.studentdata'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
